[workspace]
resolver = "2"
members = ["crates/conch-core"]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
ed25519-dalek = "2.2.0"
hex = "0.4.3"
ryu-js = "1.0.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["float_roundtrip"] }
sha2 = "0.10.9"
thiserror = "2.0.18"
