[package]
name = "conch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
conch-core = { path = "../conch-core" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true

[dev-dependencies]
conchd = { path = "../conchd" }
tempfile.workspace = true
