[package]
name = "conchd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
conch-core = { path = "../conch-core" }
ed25519-dalek.workspace = true
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
thiserror.workspace = true
axum.workspace = true
futures-util.workspace = true
axum-server.workspace = true
tokio-rustls.workspace = true
rustls-pemfile.workspace = true
rustls-native-certs.workspace = true
subtle.workspace = true
url.workspace = true
tokio-tungstenite = { version = "0.29.0", features = ["rustls-tls-native-roots"] }

[dev-dependencies]
tempfile.workspace = true
rcgen = "0.14.5"
tokio = { workspace = true, features = ["test-util"] }
